version: "3.0"
services:
  user:
    build:
      context: ./user
    ports:
      - 80:80

  dashboard:
    build:
      context: ./dashboard
    ports:
      - 81:80

  shop:
    build:
      context: ./shop
    ports:
      - 82:80


networks:
  docker-service:
    driver: bridge
